# -*- coding: utf-8 -*-
"""Speech to text.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1svAdWQ4RwzKa0CZ1YC2GxX1C_zXkI-jH
"""
import json

import assemblyai as aai

# set the API key
aai.settings.api_key = "d16################9f0f"

transcriber = aai.Transcriber()


#transcript = transcriber.transcribe("/content/sample-1.mp3")
#print(transcript.text)

#transcript.audio_duration

#for sentence in transcript.get_sentences():
#  print(sentence.text)

#pickle.dump(transcriber, open('stt.pkl', 'wb'))

